---
  LISTEN_HOST: 0.0.0.0
  LISTEN_PORT: 53535
  LOGS_FOLDER: /data/test3/dnsr3/
  
  PROXY_CLASS: SimpleDNSRequestHandler
  DEFAULT_DNS_SERVER: 208.67.222.222:53
  UPSTREAM_SERVERS: 

  QUERY_TIMEOUT: 4
  QUERY_RETRIES: 3