---
  LISTEN_HOST: 0.0.0.0
  LISTEN_PORT: 53535
  LOGS_FOLDER: /data/test8/dnsr2/
  
  PROXY_CLASS: SimpleDNSRequestHandler
  DEFAULT_DNS_SERVER: 9.9.9.9:53
  UPSTREAM_SERVERS: 

  QUERY_TIMEOUT: 6
  QUERY_RETRIES: 3
