---
  LISTEN_HOST: 0.0.0.0
  LISTEN_PORT: 53535
  LOGS_FOLDER: /data/test7/dnsr4/
  
  PROXY_CLASS: SimpleDNSRequestHandler
  DEFAULT_DNS_SERVER: pdns_recursor:53
  UPSTREAM_SERVERS: 

  QUERY_TIMEOUT: 1
  QUERY_RETRIES: 3