---
  LISTEN_HOST: 0.0.0.0
  LISTEN_PORT: 53535
  LOGS_FOLDER: /data/test1/dnsr1/
  
  PROXY_CLASS: SimpleDNSRequestHandler
  DEFAULT_DNS_SERVER: 1.1.1.1:53
  UPSTREAM_SERVERS: 

  QUERY_TIMEOUT: 2
  QUERY_RETRIES: 3